name: SecurityMonkey
description: An AWS Policy Monitoring Tool
dependencies:
  angular: '0.12.0'
  browser: '0.10.0+2'
  http_server: '0.9.2+2'
  angular_ui: '0.5.5'
  hammock: '>=0.2.4 <0.3.0'
  ng_infinite_scroll: ">=0.1.1 <0.2.0"
dev_dependencies:
  unittest: '0.11.0+2'
# Transformers are breaking the ng_infinite_scroll
# https://bitbucket.org/evidentsolutions/dart-ng-infinite-scroll/issue/2/expression-binded-to-infinite-scroll-is
#transformers:
# - angular
# - $dart2js:
#    minify: true

